export const CHOOSE_SERVER_GROUP = 'CHOOSE_SERVER_GROUP';
export const CHOOSE_SERVER = 'CHOOSE_SERVER';
export const CHOOSE_SEARCH_CONDITIONS = 'CHOOSE_SEARCH_CONDITIONS';
export const CHOOSE_STATE_AREA = 'CHOOSE_STATE_AREA';